# Use an official lightweight Python image
FROM python:3.10-slim

# Set the working directory inside container
WORKDIR /app

# Copy local files into the container
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the Flask app port
EXPOSE 5000

# Command to start the app
CMD ["python", "app.py"]

